### ISSUE TITLE
the document about gnu makefiles has a tiny (but significant) mistake

### ISSUE THREAD

**Issue by zlago** [dreamportdev/Osdev-Notes#86]
the document claims GNU `make` looks for `GNUMakefile` (uppercase `M`), its actually `GNUmakefile` (lowercase `m`)
```
$ touch GNUMakefile
$ make
make: *** No targets specified and no makefile found.  Stop.
$ touch GNUmakefile
$ make
make: *** No targets.  Stop.
```

**Comment by dreamos82** [comment]
Thanks for reporting it, @zlago, wow that was hard to spot! :) 

I can fix it on a branch I've created with few other fixes. But if you want contribute, feel free to open a PR and me or @DeanoBurrito  will merge it! (my branch will not be merged soon).

Thanks again!

**Comment by dreamos82** [comment]
Hi @zlago i've added the change you suggeste in a branch with other fixed. It will be merged soon(er or later :))
Thanks again for reporting! I'll close the issue once the fix will be merged into master)

**Comment by dreamos82** [comment]
Hi @zlago i made the change in PR #88, so i'm going to close this issue. Thanks
